---
title: Michael Schneider
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
tagline: CV & Blog
description: My Personal Website
url: https://schneidercode.github.io
baseurl: ''
paginate: 5
author:
  name: Michael Schneider
  url: https://www.linkedin.com/in/michael-schneider-2156b5a8/
plugins:
- jekyll-paginate
- jekyll-gist
version: 3.0.0
